[package]
name = "rust-embed"
version = "5.9.0"
description = "Rust Custom Derive Macro which loads files into the rust binary at compile time during release and loads the file from the fs during dev"
readme = "readme.md"
documentation = "https://docs.rs/rust-embed"
repository = "https://github.com/pyros2097/rust-embed"
license = "MIT"
keywords = ["http", "rocket", "static", "web", "server"]
categories = ["web-programming", "filesystem"]
authors = ["pyros2097 <pyros2097@gmail.com>"]
edition = "2018"

[[example]]
name = "warp"
path = "examples/warp.rs"
required-features = ["warp-ex"]

[[example]]
name = "actix"
path = "examples/actix.rs"
required-features = ["actix"]

[[example]]
name = "rocket"
path = "examples/rocket.rs"
required-features = ["rocket"]

[[test]]
name = "interpolated_path"
path = "tests/interpolated_path.rs"
required-features = ["interpolate-folder-path"]

[dependencies]
walkdir = "2.3.1"
rust-embed-impl = { version = "5.9.0", path = "impl"}
rust-embed-utils = { version = "5.1.0", path = "utils"}

include-flate = { version = "0.1", optional = true, features = ["stable"] }
actix-web = { version = "3", default-features = false, optional = true }
mime_guess = { version = "2", optional = true }
tokio = { version = "0.2", optional = true, features = ["macros"] }
warp = { version = "0.2", default-features = false, optional = true }
rocket = { version = "0.4.5", default-features = false, optional = true }

[features]
debug-embed = ["rust-embed-impl/debug-embed", "rust-embed-utils/debug-embed"]
interpolate-folder-path = ["rust-embed-impl/interpolate-folder-path"]
compression = ["rust-embed-impl/compression", "include-flate"]
nightly = ["rocket"]
actix = ["actix-web", "mime_guess"]
warp-ex = ["warp", "tokio", "mime_guess"]

[badges]
appveyor = { repository = "pyros2097/rust-embed" }
travis-ci = { repository = "pyros2097/rust-embed" }
is-it-maintained-issue-resolution = { repository = "pyros2097/rust-embed" }
is-it-maintained-open-issues = { repository = "pyros2097/rust-embed" }
maintenance = { status = "passively-maintained" }

[workspace]
members = ["impl", "utils"]
